### ISSUE TITLE
After upgrade from 0.1.0 to 0.2.0 it stops working

### ISSUE THREAD

**Issue by uhlhosting** [Brodan/patter#4]
Hi,

I have tried to upgrade it. And the following occured, notice last version worked fine.
```
Revenger:patter-0.1.0.dist-info cosmicsound$ pip install patter --upgrade
Collecting patter
  Downloading https://files.pythonhosted.org/packages/43/48/ffb0fed9e55970677c7e87e9787ccc2d36022ef3f424db3e59c7fccc635e/patter-0.2.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: mattermostdriver>=5.0.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from patter) (5.0.0)
Requirement already satisfied, skipping upgrade: websockets>=3.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from mattermostdriver>=5.0.0->patter) (6.0)
Requirement already satisfied, skipping upgrade: requests>=2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from mattermostdriver>=5.0.0->patter) (2.19.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.1->mattermostdriver>=5.0.0->patter) (2018.4.16)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.1->mattermostdriver>=5.0.0->patter) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3<1.24,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.1->mattermostdriver>=5.0.0->patter) (1.23)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.1->mattermostdriver>=5.0.0->patter) (2.7)
Installing collected packages: patter
  Found existing installation: patter 0.1.0
    Uninstalling patter-0.1.0:
      Successfully uninstalled patter-0.1.0
Successfully installed patter-0.2.0
Revenger:patter-0.1.0.dist-info cosmicsound$ history | grep echo
  301  echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
  345  echo "testing" | patter -c town-square
  360  echo "testing" | patter -c town-square
  368  echo "testing" | patter -c town-square
  371  echo "testing" | patter -c town-square
  374  echo "testing" | patter -c town-square
  377  echo "testing" | patter -c town-square
  379  echo "testing" | patter -c town-square
  380  echo "testing" | patter -c town-square
  383  echo "testing" | patter -c town-square
  386  echo "testing" | patter -c town-square
  389  echo "testing" | patter -c town-square
  390  cd '/Users/cosmicsound/Documents/GitHub/patter/' && '/usr/local/bin/pythonw'  '/Users/cosmicsound/Documents/GitHub/patter/setup.py'  && echo Exit status: $? && exit 1
  391  cd '' && '/usr/local/bin/pythonw' -d -v -i -O -t  '<your script here>'  && echo Exit status: $? && exit 1
  392  cd '/Users/cosmicsound/Documents/GitHub/patter/' && '/usr/local/bin/pythonw'  '/Users/cosmicsound/Documents/GitHub/patter/setup.py'  && echo Exit status: $? && exit 1
  522  history | grep echo
Revenger:patter-0.1.0.dist-info cosmicsound$ echo "testing" | patter -c town-square
-bash: /Library/Frameworks/Python.framework/Versions/3.7/bin/patter: /Users/chranj/homebrew/opt/python/bin/python3.7: bad interpreter: No such file or directory
Revenger:patter-0.1.0.dist-info cosmicsound$ echo "testing" | patter -c town-square
-bash: /Library/Frameworks/Python.framework/Versions/3.7/bin/patter: /Users/chranj/homebrew/opt/python/bin/python3.7: bad interpreter: No such file or directory
Revenger:patter-0.1.0.dist-info cosmicsound$ 

```

Note that this path:

/Users/**chranj/homebrew/opt**/python/bin/python3.7

Become embedded in the install process somehow
I do not have such username on my mac.

Best
Cosmin

**Comment by Brodan** [comment]
Hi @uhlhosting,

Sorry for causing more issues! Can you tell its my first python package? :(
It looks like something got screwed up during packaging. Obviously that line shouldn't be there. Let me figure out how to fix it.

**Comment by Brodan** [comment]
@uhlhosting I removed 0.2.0 from PyPI and pushed 0.2.1, try that and let me know if it's still broken. I tested on an Ubuntu laptop and it seemed to install just fine so hopefully I fixed the problem.

**Comment by uhlhosting** [comment]
@Brodan It works this version, alto I found something that can be improved at least to display a nice instructing error. I am not sure what caused it, I think it might be the limitations from mattermost for the lenght of the message. I paste the log here: https://gist.github.com/uhlhosting/7f3a4ee0f54af3bceee171a1c0c9e802

`Revenger:~ cosmicsound$ systemstats | patter -c town-square
Invalid message
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mattermostdriver/client.py", line 140, in make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://chat.uhlhosting.ch:443/api/v4/posts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/patter", line 60, in <module>
    patter.send_message()
  File "/usr/local/lib/python3.7/site-packages/patter/patter.py", line 86, in send_message
    self.mm_client.posts.create_post(options)
  File "/usr/local/lib/python3.7/site-packages/mattermostdriver/endpoints/posts.py", line 13, in create_post
    options=options
  File "/usr/local/lib/python3.7/site-packages/mattermostdriver/client.py", line 169, in post
    return self.make_request('post', endpoint, options=options, params=params, data=data, files=files).json()
  File "/usr/local/lib/python3.7/site-packages/mattermostdriver/client.py", line 145, in make_request
    raise InvalidOrMissingParameters(data['message'])
mattermostdriver.exceptions.InvalidOrMissingParameters: Invalid message`

**Comment by uhlhosting** [comment]
I know what is the purpose of last issue, the stder was huge output. This can be marked as solved, while the initial issue was solved in the newer release.
